language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.0.*

jobs:
    exclude:
        -
            php: '7.1'
            env: SYMFONY_VERSION=5.0.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require symfony/proxy-manager-bridge:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist

    - composer require --dev symfony/browser-kit:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require --dev symfony/framework-bundle:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require --dev symfony/process:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require --dev symfony/yaml:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist

    - if [ "$SYMFONY_VERSION" = "5.0.*" ]; then composer require --dev behat/behat:dev-master --no-update --no-scripts --prefer-dist; fi

    - composer update --prefer-dist

script:
    - composer check

    - vendor/bin/behat -f progress --strict -vvv --no-interaction
